// =============================================================================
// Office Registry — Build-time office list for workspace generation
// =============================================================================
// This is the source of truth for which offices get workspaces.
// In production, this is generated from Sanity data at build time
// (via scripts/generate-offices.ts). Studio rebuild on office changes.
//
// Each entry maps to one Sanity workspace with:
//   - Scoped Structure Builder (GROQ filters by office._ref)
//   - Initial value templates (auto-set office reference)
//   - Presentation tool routes (office-specific preview URLs)
// =============================================================================

export interface OfficeEntry {
  /** Sanity document _id for this office */
  id: string
  /** Human-readable name (workspace title) */
  name: string
  /** URL-safe slug (workspace name + basePath) */
  slug: string
  /** Frontend domain for Presentation tool preview */
  domain: string
  /** City for workspace subtitle / grouping */
  city: string
}

// =============================================================================
// Placeholder registry — replace with generated data in production
// =============================================================================
// In production, this array is generated by scripts/generate-offices.ts
// which queries Sanity for all office documents and outputs this file.
//
// Usage:
//   1. npx tsx scripts/generate-offices.ts
//   2. Commit the updated office-registry.ts
//   3. Deploy Studio (triggers rebuild with new workspace list)
// =============================================================================

export const offices: OfficeEntry[] = [
  {
    id: 'office-atlantis-yaletown',
    name: 'Atlantis Dental Yaletown',
    slug: 'atlantis-yaletown',
    domain: 'https://atlantis-yaletown.123dentist.com',
    city: 'Vancouver',
  },
  {
    id: 'office-broadway-smiles',
    name: 'Broadway Smiles',
    slug: 'broadway-smiles',
    domain: 'https://broadway-smiles.123dentist.com',
    city: 'Vancouver',
  },
  {
    id: 'office-alpha-dental',
    name: 'Alpha Dental Clinic',
    slug: 'alpha-dental',
    domain: 'https://alpha-dental.123dentist.com',
    city: 'Montréal',
  },
]
